FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# ARG NEXT_PROJECT_NAME
# ARG NEXT_PUBLIC_GITHUB_USERNAME
# ARG NEXT_PUBLIC_GITHUB_ID
# ARG NEXT_PUBLIC_GITHUB_AVATAR
# ARG NEXT_PUBLIC_X_USERNAME
# ARG NEXT_PUBLIC_DISCORD_USERNAME

# ENV NEXT_PROJECT_NAME=${NEXT_PROJECT_NAME}
# ENV NEXT_PUBLIC_GITHUB_USERNAME=${NEXT_PUBLIC_GITHUB_USERNAME}
# ENV NEXT_PUBLIC_GITHUB_ID=${NEXT_PUBLIC_GITHUB_ID}
# ENV NEXT_PUBLIC_GITHUB_AVATAR=${NEXT_PUBLIC_GITHUB_AVATAR}
# ENV NEXT_PUBLIC_X_USERNAME=${NEXT_PUBLIC_X_USERNAME}
# ENV NEXT_PUBLIC_DISCORD_USERNAME=${NEXT_PUBLIC_DISCORD_USERNAME}

# Telemetry
ENV NEXT_TELEMETRY_DISABLED 1

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . /usr/src/app

RUN npm run build

# EXPOSE 3069

# -- is used to pass arguments to the npm start script
CMD ["npm", "run", "start", "--", "-p", "3069"]